# Generated by Django 4.0.4 on 2022-06-13 13:43

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_category', models.CharField(choices=[('O', 'Outdoor'), ('I', 'Indoor'), ('F', 'Flower'), ('ALL', 'No category')], default='ALL', max_length=3)),
                ('title', models.TextField(max_length=30)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=100)),
                ('plant_image', models.ImageField(default='default_plant_image.jpg', upload_to='plant_pics')),
                ('price', models.FloatField(default='0.00', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price in €')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
